#! /bin/sh 
#
#   AMQP conformance tests
#
#   This script runs the AMQP conformance tests.


function die() {
    echo "E: $@"
    echo "I: aborting conformance tests"
    exit -1
}

if [ "$IBASE" = "" ]; then
    die "IBASE not set"
fi

if [ "$COLOR" = "no" ]; then
    unset GREEN RED RESET
else
    GREEN=$'\e[32;02m'
    RED=$'\e[31;02m'
    YELLOW=$'\e[33;01m'
    RESET=$'\e[37;00m'
fi

if [ "x$1" = "x" ]; then
    LOG="lastrun.log"
else
    LOG=$1
fi
echo -n > $LOG

if [ -e works.pal ] && [ -e fails.pal ]; then
    if [ -e "compare.log" ]; then
        echo "initializing using compare.log ..."
        echo "[ CUR  ] [ PREV ] description of test"
    else
        echo "initializing ... (to compare: ln -s log/results_to_compare.log compare.log)"
        echo "[ CUR  ] description of test"
    fi

    if [ "works.pal" -nt "works" ]; then
        pal works.pal &>/dev/null
    fi
    ./works &>/dev/null || die "could not initialise (positive test failed)"

    if [ "fails.pal" -nt "fails" ]; then
        pal fails.pal &>/dev/null
    fi
    ./fails &>/dev/null && die "could not initialise (negative test failed)"
else
    echo "no works/fails pal scripts found... continuing w/o initial test"
fi


for testcase in `ls *.pal|grep -v amq_test_base.pal|grep -v works.pal|grep -v fails.pal|grep -v breakage`; do
    if test "$(grep "not implemented" $testcase)" = ""; then 
        DESC=`cat $testcase|grep desc|perl -ne 's/^\s*desc\s*=\s"(.*?)"\s*/$1/; print $_'`
        COMP=" "
        MD5=`md5sum $testcase`
        if [ $testcase -nt ${testcase%%.pal} ]; then
            pal $testcase &>/dev/null 
            if [ $? -eq 0 ]; then 
                COMP=" (${YELLOW}compiling OK$RESET) "
            else
                COMP=" (${RED}compile FAILED$RESET) "
            fi
        fi
    
        killall -9 amq_server &>/dev/null && echo -n "(${RED}lingering server killed${RESET})" || echo -n
        ./${testcase%%.pal} &>/dev/null
        if [ $? -eq 0 ]; then
            STAT="[ $GREEN OK $RESET ]"
            LSTAT="OK   "
        else
            STAT="[$RED FAIL $RESET]"
            LSTAT="FAIL "
        fi
        echo "$LSTAT $MD5" >> $LOG
        if [ -e "compare.log" ]; then
            PSTAT=`cat compare.log | grep "$MD5" | cut -d\  -f1`
            if [ "x$PSTAT" = "xOK" ]; then
                PSSTAT="[ $GREEN OK $RESET ]"
            elif [ "x$PSTAT" = "xFAIL" ]; then
                PSSTAT="[$RED FAIL $RESET]"
            else
                PSSTAT="[   ?  ]"
            fi    
            echo -n "$STAT $PSSTAT $testcase:$COMP$DESC... "
        else
            echo -n "$STAT $testcase:$COMP$DESC... "
        fi
        # only temporary solution, pal needs to make sure the server is down
        killall -9 amq_server &>/dev/null && echo "(${RED}lingering server killed${RESET})" || echo
    fi
done

