#! /usr/bin/perl
#=============================================================================
#
#   AMQConnectionState.pl - description of Perl program
#
#   Written:     6/08/31  Your Name
#   Revised:     6/08/31
#
#   Skeleton generated by LIBERO 2.4 on 31 Aug, 2006,  8:54.
#=============================================================================

use warnings;
use IO::Socket;

use Log::Log4perl qw(get_logger :levels);

use AMQP::Framing::EncodingUtils;
use AMQP::Framing::ProtocolInitiation;

$socket = new IO::Socket(
    Domain   => PF_INET,
    Proto     => 'tcp',
    PeerAddr => "localhost",
    PeerPort => 5672,
);

$logger = get_logger("AMQP::Framing::EncodingUtils");
$codec_util = new AMQP::Framing::EncodingUtils($socket);
$pi = new AMQP::Framing::ProtocolInitiation();

require 'AMQConnectionState.d';         #   Include dialog interpreter

##########################   INITIALISE THE PROGRAM   #########################

sub initialise_the_program
{
    $the_next_event = $ok_event;
}


############################   GET EXTERNAL EVENT   ###########################

sub get_external_event
{
}


##########################   TERMINATE THE PROGRAM    #########################

sub terminate_the_program
{
    $the_next_event = $terminate_event;
}


#########################   SEND PROTOCOL INITIATION   ########################

sub send_protocol_initiation
{
    $pi->write_protocol_initiation($codec_util);

    $the_next_event = $terminate_event;
}


###############################   EXPECT FRAME   ##############################

sub expect_frame
{
}


###########################   CONNECTION CLOSE OK   ###########################

sub connection_close_ok
{
}


###########################   CONNECTION START OK   ###########################

sub connection_start_ok
{
}


############################   CONNECTION TUNE OK   ###########################

sub connection_tune_ok
{
}


#############################   CONNECTION OPEN   #############################

sub connection_open
{
}


########################   CONNECTION OPEN OK HANDLER   #######################

sub connection_open_ok_handler
{
}


############################   CONNECTION CLOSED   ############################

sub connection_closed
{
}


#################################   CLEANUP   #################################

sub cleanup
{
}

