#!/bin/sh

if test "$(which javac)" != ""; then
    if test -f javax/jms/Connection.java; then
        javac javax/jms/*.java
        jar -cf jms.jar javax/jms/*.class        
        exit 0
    else
        echo ""
        echo "You need to:"    
        echo "1. Get SUN's JMS 'source' from http://java.sun.com/products/jms/docs.html"    
        echo "2. Move SUN's JMS interfaces to javax/jms"    
        exit 1
    fi
else
    echo ""
    echo "Cannot find the java sdk"    
    exit 1
fi

