#! /bin/sh
#

# Requirements:
# dia >= 0.94.0-7
# epstopdf (tetex-bin)
# epsffit (psutils)

# Scale factor for the PDF target
scale=46

# Get pdf from eps
get_pdf()
{
    epsffit -c 0 0 $((($4 - $2) * $scale / 100)) $((($5 - $3) * $scale / 100)) $6.eps > scaled.$6.eps
    epstopdf --outfile=$6.pdf scaled.$6.eps
    rm -f scaled.$6.eps
}

#   Build PNG from dia file
FILE=`basename $1 .dia`
dia -e $FILE.png $FILE.dia

#   Build PDF from dot file
dia --export-to-format=eps-builtin $FILE.dia
get_pdf $(grep %BoundingBox $FILE.eps) $FILE
