/*---------------------------------------------------------------------------*
 *  lrload.d - LIBERO dialog data definitions for lrload.c.                  *
 *  Generated by LIBERO 2.4 on 20 Mar, 2012, 15:06.                          *
 *  Schema file used: lrschema.c.                                            *
 *---------------------------------------------------------------------------*/

/*- Symbolic constants and event numbers ------------------------------------*/

#define _LR_STOP                        0xFFFFL
#define _LR_NULL_EVENT                  -2
enum {
    terminate_event = -1,
    comment_event = 0,
    error_event = 1,
    event_number_event = 2,
    item_name_event = 3,
    module_flag_event = 4,
    next_pointer_event = 5,
    no_more_event = 6,
    ok_event = 7,
    option_event = 8,
    state_name_event = 9,
    state_name_term_event = 10,
    superstate_ref_event = 11
};

enum {
    _LR_defaults_state = 9,
    _LR_STATE_after_init = 0,
    _LR_STATE_expect_state_name = 1,
    _LR_STATE_after_state = 2,
    _LR_STATE_expect_event_name = 3,
    _LR_STATE_expect_next_pointer = 4,
    _LR_STATE_after_next_pointer = 5,
    _LR_STATE_after_event = 6,
    _LR_STATE_after_module_flag = 7,
    _LR_STATE_after_module = 8,
    _LR_STATE_defaults = 9
};


/*- Variables used by dialog interpreter ------------------------------------*/

typedef int event_t;                    /*  Type for dialog entity           */
typedef int state_t;                    /*  Type for dialog entity           */
typedef void (fsmfunct) (void);         /*  Address of FSM function          */

static event_t
    _LR_event,                          /*  Event for state transition       */
    the_next_event,                     /*  Next event from module           */
    the_exception_event;                /*  Exception event from module      */

static state_t
    _LR_state,                          /*  Current dialog state             */
    _LR_savest;                         /*  Saved dialog state               */

static int
    _LR_index,                          /*  Index into vector table          */
    _LR_number;                         /*  Number of next module            */

static Bool
    exception_raised;                   /*  TRUE if exception raised         */

/*- Function prototypes -----------------------------------------------------*/

#ifndef MODULE
#define MODULE  static void             /*  Libero dialog modules            */
#endif

static void raise_exception             (event_t event);
MODULE initialise_the_program           (void);
MODULE get_external_event               (void);
MODULE open_dialog_file                 (void);
MODULE expect_state_name                (void);
MODULE get_next_token                   (void);
MODULE attach_new_state                 (void);
MODULE expect_state_definition          (void);
MODULE warning_on_state_name            (void);
MODULE attach_uses_superstate           (void);
MODULE store_event_number               (void);
MODULE expect_event_name                (void);
MODULE attach_new_event                 (void);
MODULE expect_next_pointer              (void);
MODULE expect_event_definition          (void);
MODULE attach_same_next_state           (void);
MODULE expect_module_name               (void);
MODULE attach_next_state                (void);
MODULE attach_empty_module              (void);
MODULE expand_macro_constructs          (void);
MODULE build_source_file_name           (void);
MODULE close_dialog_file                (void);
MODULE terminate_the_program            (void);
MODULE attach_new_module                (void);
MODULE display_unexpected_token         (void);
MODULE return_error_feedback            (void);
MODULE process_option_value             (void);
MODULE process_comment_value            (void);

/*- Static areas ------------------------------------------------------------*/

static dbyte _LR_nextst [][12] =
{
    { 0,0,0,0,0,0,0,1,0,0,0,0 },
    { 0,0,0,2,0,0,0,0,0,2,0,0 },
    { 0,0,3,2,0,0,0,0,0,2,2,2 },
    { 0,0,0,4,0,0,0,0,0,0,0,0 },
    { 0,0,0,0,7,5,0,0,0,0,0,0 },
    { 0,0,3,6,7,0,5,0,0,2,0,0 },
    { 0,0,3,2,7,0,0,0,0,2,0,0 },
    { 0,0,3,8,0,0,7,0,0,2,0,0 },
    { 0,0,3,2,7,0,0,0,0,2,0,0 },
    { 9,9,9,9,9,9,9,0,9,9,9,9 }
};

static dbyte _LR_action [][12] =
{
    { 0,0,0,0,0,0,0,1,0,0,0,0 },
    { 0,0,0,3,0,0,0,0,0,2,0,0 },
    { 0,0,5,3,0,0,0,0,0,2,6,4 },
    { 0,0,0,7,0,0,0,0,0,0,0,0 },
    { 0,0,0,0,9,8,0,0,0,0,0,0 },
    { 0,0,12,10,9,0,13,0,0,11,0,0 },
    { 0,0,15,17,16,0,0,0,0,14,0,0 },
    { 0,0,15,18,0,0,19,0,0,14,0,0 },
    { 0,0,5,3,16,0,0,0,0,2,0,0 },
    { 22,23,20,20,20,20,24,0,21,20,20,20 }
};

static dbyte _LR_vector [][6+1] =
{
    {0},
    {0,1,2,_LR_STOP},
    {3,4,2,_LR_STOP},
    {5,3,4,2,_LR_STOP},
    {6,4,2,_LR_STOP},
    {7,8,2,_LR_STOP},
    {2,_LR_STOP},
    {9,10,2,_LR_STOP},
    {11,2,_LR_STOP},
    {12,13,2,_LR_STOP},
    {14,2,_LR_STOP},
    {12,15,3,4,2,_LR_STOP},
    {12,15,7,8,2,_LR_STOP},
    {12,15,16,17,18,19,_LR_STOP},
    {15,3,4,2,_LR_STOP},
    {15,7,8,2,_LR_STOP},
    {13,2,_LR_STOP},
    {15,5,3,4,2,_LR_STOP},
    {20,2,_LR_STOP},
    {15,16,17,18,19,_LR_STOP},
    {21,18,22,19,_LR_STOP},
    {23,2,_LR_STOP},
    {24,2,_LR_STOP},
    {18,22,19,_LR_STOP},
    {16,17,18,19,_LR_STOP}
};

static fsmfunct *_LR_module [] =
{
    open_dialog_file,
    expect_state_name,
    get_next_token,
    attach_new_state,
    expect_state_definition,
    warning_on_state_name,
    attach_uses_superstate,
    store_event_number,
    expect_event_name,
    attach_new_event,
    expect_next_pointer,
    expect_event_definition,
    attach_same_next_state,
    expect_module_name,
    attach_next_state,
    attach_empty_module,
    expand_macro_constructs,
    build_source_file_name,
    close_dialog_file,
    terminate_the_program,
    attach_new_module,
    display_unexpected_token,
    return_error_feedback,
    process_option_value,
    process_comment_value
};

