@echo off
:-
:-  Boom builder for iMatix Base1 1.2e0
:-  Generated by iMatix Boom from product.pwl
:-  
:-  Copyright (c) 1996-2009 iMatix Corporation
:-  All rights reserved.
:-  
:-  This file is licensed under the BSD license as follows:
:-  
:-  Redistribution and use in source and binary forms, with or without
:-  modification, are permitted provided that the following conditions
:-  are met:
:-  
:-  * Redistributions of source code must retain the above copyright
:-    notice, this list of conditions and the following disclaimer.
:-  * Redistributions in binary form must reproduce the above copyright
:-    notice, this list of conditions and the following disclaimer in
:-    the documentation and/or other materials provided with the
:-    distribution.
:-  * Neither the name of iMatix Corporation nor the names of its
:-    contributors may be used to endorse or promote products derived
:-    from this software without specific prior written permission.
:-  
:-  THIS SOFTWARE IS PROVIDED BY IMATIX CORPORATION "AS IS" AND ANY
:-  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
:-  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
:-  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL IMATIX CORPORATION BE
:-  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
:-  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
:-  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
:-  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
:-  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
:-  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
:-  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
:-
:-  Start CMD.EXE version detection
verify other 2>nul
setlocal enableextensions
if errorlevel 0 goto __cmd_ok
echo %0: This command requires command extensions version 2 in CMD.EXE.
echo %0: Please use a supported system (Windows 2000 or newer).
exit
:__cmd_ok
setlocal enabledelayedexpansion
:-  End CMD.EXE version detection
goto :init
:-
:-  Subroutine: boom_model_init
:-  Initialises BOOM_MODEL to default if not set
:-  Expands BOOM_MODEL components into individual environment variables
:-
:boom_model_init
if "!BOOM_MODEL!"=="" (
    set BOOM_MODEL=release,st
)
set BOOM_MODEL__PLACEHOLDER=1
for /f "usebackq delims==" %%v in (`set BOOM_MODEL_`) do set %%v=
set BOOM_MODEL__PLACEHOLDER=
for %%m in (!BOOM_MODEL!) do set BOOM_MODEL_%%m=1
:-  If the user set BOOM_MODEL but did not include release/debug or st/mt
:-  set these to defaults.
if not "!BOOM_MODEL_RELEASE!"=="1" (
    if not "!BOOM_MODEL_DEBUG!"=="1" (
        set BOOM_MODEL_RELEASE=1
        set BOOM_MODEL=!BOOM_MODEL!,release
    )
)
if not "!BOOM_MODEL_ST!"=="1" (
    if not "!BOOM_MODEL_MT!"=="1" (
        set BOOM_MODEL_ST=1
        set BOOM_MODEL=!BOOM_MODEL!,st
    )
)
goto :eof
:init
setlocal
:-
:-  Set environment variables to point to install location
:-  Start by using final IBASE, then handle -install path
set self=%0
set MY_VERSION=1.2e0
set OLDPATH=!PATH!
set OLDPERLLIB=!PERLLIB!
if .!IBASE!==. (
    echo boom E: [base1]: The IBASE variable is not set.           Please set it to the location where iMatix Base1 should be installed.
    exit /b 1
)
if .%1==.-v (
    set BOOM_TRACE=1
    shift
)
call :boom_model_init
if .%1==.-install goto tempinst
:-  Normal use, use IBASE
    set PATH=!IBASE!\bin;!PATH!
    set PERLLIB=!IBASE!\bin;!PERLLIB!
    set INCDIR_ALT=!IBASE!\include
    set _INSTALL_ROOT=!IBASE!
    goto process

:tempinst
:-  Building product, we use -install directory first, then IBASE
    if not exist %2 (
       echo "Invalid command syntax - please contact imatix-tech"
       exit /b 1
    )
    pushd %2
    set _LOCAL_BASE=!cd!
    popd
    set PATH=!_LOCAL_BASE!\bin;!IBASE!\bin;!PATH!
    set PERLLIB=!_LOCAL_BASE!\bin;!IBASE!\bin;!PERLLIB!
    set INCDIR_ALT=!_LOCAL_BASE!\include;!IBASE!\include
    set _INSTALL_ROOT=!_LOCAL_BASE!
    shift
    shift
    goto process

:batch
    shift

:process
    set state=initial
    set event=ok
    set debug=0
    goto s_!state!

:-----------------------------   ALLGEN PROJECTS   ----------------------------

:a_allgen_projects
    pushd htmlpp
    if exist boomake.bat (
        call boomake allgen
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gurudoc
    if exist boomake.bat (
        call boomake allgen
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gaggle
    if exist boomake.bat (
        call boomake allgen
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd libero
    if exist boomake.bat (
        call boomake allgen
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    goto :eof

:---------------------   BUILD PRODUCT INSTALL PACKAGES   ---------------------

:a_build_product_install_packages
    echo boom I: [base1]: building Base Install...
    if exist _install\nul rmdir /s /q _install
    mkdir _install
    mkdir _install\lib
    mkdir _install\include
    mkdir _install\bin
    pushd htmlpp
    if exist boomake.bat (
    call boomake -install ..\_install install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gurudoc
    if exist boomake.bat (
    call boomake -install ..\_install install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gaggle
    if exist boomake.bat (
    call boomake -install ..\_install install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd libero
    if exist boomake.bat (
    call boomake -install ..\_install install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    if exist base1-!MY_VERSION! rmdir /s/q base1-!MY_VERSION!
    ren _install base1-!MY_VERSION!
    if "!BOOM_TRACE!"=="1" echo pkg_zip base1-!MY_VERSION!
    verify>nul
    call pkg_zip base1-!MY_VERSION!
    if errorlevel 1 (
        echo boom E: [base1]: 'pkg_zip base1-!MY_VERSION!' failed - stop.
        set _exception=1
        goto :eof
    )
    rmdir /s/q base1-!MY_VERSION!
    goto :eof

:----------------------   BUILD PRODUCT SOURCE PACKAGES   ---------------------

:a_build_product_source_packages
    if exist _package.lst del _package.lst
    if exist project.pdl echo project.pdl>>_package.lst
    if exist readme.txt echo readme.txt>>_package.lst
    if exist release.txt echo release.txt>>_package.lst
    if exist stamp_generate echo stamp_generate>>_package.lst
    if exist boomakew.bat echo boomakew.bat>>_package.lst
    if exist configure echo configure>>_package.lst
    if exist Makefile.unix echo Makefile.unix>>_package.lst
    if exist boomake echo boomake>>_package.lst
    if exist configure.bat echo configure.bat>>_package.lst
    if exist Makefile.win32 echo Makefile.win32>>_package.lst
    if exist boomake.bat echo boomake.bat>>_package.lst
    pushd htmlpp
    popd
    if exist htmlpp\htmlppver.pl echo htmlpp\htmlppver.pl>>_package.lst
    if exist htmlpp\htmlpp echo htmlpp\htmlpp>>_package.lst
    if exist htmlpp\guru.def echo htmlpp\guru.def>>_package.lst
    if exist htmlpp\contents.def echo htmlpp\contents.def>>_package.lst
    if exist htmlpp\macros.def echo htmlpp\macros.def>>_package.lst
    if exist htmlpp\filetype.def echo htmlpp\filetype.def>>_package.lst
    if exist htmlpp\guru_opt.fmt echo htmlpp\guru_opt.fmt>>_package.lst
    if exist htmlpp\gurutst.txt echo htmlpp\gurutst.txt>>_package.lst
    if exist htmlpp\findfile.pl echo htmlpp\findfile.pl>>_package.lst
    if exist htmlpp\sflcvdp.pl echo htmlpp\sflcvdp.pl>>_package.lst
    if exist htmlpp\sfldate.pl echo htmlpp\sfldate.pl>>_package.lst
    if exist htmlpp\shellwd.pl echo htmlpp\shellwd.pl>>_package.lst
    if exist htmlpp\textdb.pl echo htmlpp\textdb.pl>>_package.lst
    if exist htmlpp\prelude.pdl echo htmlpp\prelude.pdl>>_package.lst
    if exist htmlpp\license.gpl echo htmlpp\license.gpl>>_package.lst
    if exist htmlpp\project.pdl echo htmlpp\project.pdl>>_package.lst
    if exist htmlpp\readme.txt echo htmlpp\readme.txt>>_package.lst
    if exist htmlpp\htmlpp.l echo htmlpp\htmlpp.l>>_package.lst
    if exist htmlpp\htmlpp.d echo htmlpp\htmlpp.d>>_package.lst
    if exist htmlpp\htmlpp.bat echo htmlpp\htmlpp.bat>>_package.lst
    if exist htmlpp\stamp_generate echo htmlpp\stamp_generate>>_package.lst
    if exist htmlpp\boomakew.bat echo htmlpp\boomakew.bat>>_package.lst
    if exist htmlpp\configure echo htmlpp\configure>>_package.lst
    if exist htmlpp\Makefile.unix echo htmlpp\Makefile.unix>>_package.lst
    if exist htmlpp\boomake echo htmlpp\boomake>>_package.lst
    if exist htmlpp\configure.bat echo htmlpp\configure.bat>>_package.lst
    if exist htmlpp\Makefile.win32 echo htmlpp\Makefile.win32>>_package.lst
    if exist htmlpp\boomake.bat echo htmlpp\boomake.bat>>_package.lst
    if exist htmlpp\template\contents.def echo htmlpp\template\contents.def>>_package.lst
    if exist htmlpp\template\filetype.def echo htmlpp\template\filetype.def>>_package.lst
    if exist htmlpp\template\prelude.def echo htmlpp\template\prelude.def>>_package.lst
    if exist htmlpp\template\template.txt echo htmlpp\template\template.txt>>_package.lst
    pushd gurudoc
    popd
    if exist gurudoc\guruver.gsl echo gurudoc\guruver.gsl>>_package.lst
    if exist gurudoc\guruver.pl echo gurudoc\guruver.pl>>_package.lst
    if exist gurudoc\gdl.txt echo gurudoc\gdl.txt>>_package.lst
    if exist gurudoc\gdl.xnf echo gurudoc\gdl.xnf>>_package.lst
    if exist gurudoc\gdlcode.gsl echo gurudoc\gdlcode.gsl>>_package.lst
    if exist gurudoc\gdlparse.gsl echo gurudoc\gdlparse.gsl>>_package.lst
    if exist gurudoc\gurudoc.gsl echo gurudoc\gurudoc.gsl>>_package.lst
    if exist gurudoc\mkgdl echo gurudoc\mkgdl>>_package.lst
    if exist gurudoc\mkgdl.bat echo gurudoc\mkgdl.bat>>_package.lst
    if exist gurudoc\gurudoc echo gurudoc\gurudoc>>_package.lst
    if exist gurudoc\gurudoc.bat echo gurudoc\gurudoc.bat>>_package.lst
    if exist gurudoc\mod_gdl.gsl echo gurudoc\mod_gdl.gsl>>_package.lst
    if exist gurudoc\gd2xhtml echo gurudoc\gd2xhtml>>_package.lst
    if exist gurudoc\gd2xhtml.bat echo gurudoc\gd2xhtml.bat>>_package.lst
    if exist gurudoc\test_html_frame.gsl echo gurudoc\test_html_frame.gsl>>_package.lst
    if exist gurudoc\html_frame.gsl echo gurudoc\html_frame.gsl>>_package.lst
    if exist gurudoc\html_simple.gsl echo gurudoc\html_simple.gsl>>_package.lst
    if exist gurudoc\html_multi.gsl echo gurudoc\html_multi.gsl>>_package.lst
    if exist gurudoc\html_library.gsl echo gurudoc\html_library.gsl>>_package.lst
    if exist gurudoc\txt_simple.gsl echo gurudoc\txt_simple.gsl>>_package.lst
    if exist gurudoc\rtf_simple.gsl echo gurudoc\rtf_simple.gsl>>_package.lst
    if exist gurudoc\latex_simple.gsl echo gurudoc\latex_simple.gsl>>_package.lst
    if exist gurudoc\mod_rtf.gsl echo gurudoc\mod_rtf.gsl>>_package.lst
    if exist gurudoc\texi_simple.gsl echo gurudoc\texi_simple.gsl>>_package.lst
    if exist gurudoc\groff_simple.gsl echo gurudoc\groff_simple.gsl>>_package.lst
    if exist gurudoc\ooo_document.gsl echo gurudoc\ooo_document.gsl>>_package.lst
    if exist gurudoc\ooo_whitepaper.gsl echo gurudoc\ooo_whitepaper.gsl>>_package.lst
    if exist gurudoc\tpl_frame.htm echo gurudoc\tpl_frame.htm>>_package.lst
    if exist gurudoc\tpl_frame_body.htm echo gurudoc\tpl_frame_body.htm>>_package.lst
    if exist gurudoc\tpl_frame_bot.htm echo gurudoc\tpl_frame_bot.htm>>_package.lst
    if exist gurudoc\tpl_frame_top.htm echo gurudoc\tpl_frame_top.htm>>_package.lst
    if exist gurudoc\tpl_frame_toc.htm echo gurudoc\tpl_frame_toc.htm>>_package.lst
    if exist gurudoc\tpl_simple.htm echo gurudoc\tpl_simple.htm>>_package.lst
    if exist gurudoc\tpl_document.sxw echo gurudoc\tpl_document.sxw>>_package.lst
    if exist gurudoc\tpl_whitepaper.sxw echo gurudoc\tpl_whitepaper.sxw>>_package.lst
    if exist gurudoc\tpl_latex.tex echo gurudoc\tpl_latex.tex>>_package.lst
    if exist gurudoc\html_frameset.gsl echo gurudoc\html_frameset.gsl>>_package.lst
    if exist gurudoc\tpl_frameset.htm echo gurudoc\tpl_frameset.htm>>_package.lst
    if exist gurudoc\tpl_frameset_body.htm echo gurudoc\tpl_frameset_body.htm>>_package.lst
    if exist gurudoc\tpl_frameset_bot.htm echo gurudoc\tpl_frameset_bot.htm>>_package.lst
    if exist gurudoc\tpl_frameset_top.htm echo gurudoc\tpl_frameset_top.htm>>_package.lst
    if exist gurudoc\tpl_frameset_toc.htm echo gurudoc\tpl_frameset_toc.htm>>_package.lst
    if exist gurudoc\wikidot.gsl echo gurudoc\wikidot.gsl>>_package.lst
    if exist gurudoc\gddoc.txt echo gurudoc\gddoc.txt>>_package.lst
    if exist gurudoc\gddoc.gdl echo gurudoc\gddoc.gdl>>_package.lst
    if exist gurudoc\gddoc*.html echo gurudoc\gddoc*.html>>_package.lst
    if exist gurudoc\mainlogo.jpg echo gurudoc\mainlogo.jpg>>_package.lst
    if exist gurudoc\gdstyle.css echo gurudoc\gdstyle.css>>_package.lst
    if exist gurudoc\prelude.pdl echo gurudoc\prelude.pdl>>_package.lst
    if exist gurudoc\license.gpl echo gurudoc\license.gpl>>_package.lst
    if exist gurudoc\project.pdl echo gurudoc\project.pdl>>_package.lst
    if exist gurudoc\readme.txt echo gurudoc\readme.txt>>_package.lst
    if exist gurudoc\stamp_generate echo gurudoc\stamp_generate>>_package.lst
    if exist gurudoc\boomakew.bat echo gurudoc\boomakew.bat>>_package.lst
    if exist gurudoc\configure echo gurudoc\configure>>_package.lst
    if exist gurudoc\Makefile.unix echo gurudoc\Makefile.unix>>_package.lst
    if exist gurudoc\boomake echo gurudoc\boomake>>_package.lst
    if exist gurudoc\configure.bat echo gurudoc\configure.bat>>_package.lst
    if exist gurudoc\Makefile.win32 echo gurudoc\Makefile.win32>>_package.lst
    if exist gurudoc\boomake.bat echo gurudoc\boomake.bat>>_package.lst
    if exist gurudoc\liblocal.vcproj echo gurudoc\liblocal.vcproj>>_package.lst
    pushd gaggle
    popd
    if exist gaggle\framer echo gaggle\framer>>_package.lst
    if exist gaggle\framer.fmt echo gaggle\framer.fmt>>_package.lst
    if exist gaggle\srcdoc echo gaggle\srcdoc>>_package.lst
    if exist gaggle\srcdoc.fmt echo gaggle\srcdoc.fmt>>_package.lst
    if exist gaggle\srcdoc.man echo gaggle\srcdoc.man>>_package.lst
    if exist gaggle\objtype.gsl echo gaggle\objtype.gsl>>_package.lst
    if exist gaggle\framer.l echo gaggle\framer.l>>_package.lst
    if exist gaggle\framer.d echo gaggle\framer.d>>_package.lst
    if exist gaggle\framer.bat echo gaggle\framer.bat>>_package.lst
    if exist gaggle\srcdoc.l echo gaggle\srcdoc.l>>_package.lst
    if exist gaggle\srcdoc.d echo gaggle\srcdoc.d>>_package.lst
    if exist gaggle\srcdoc.bat echo gaggle\srcdoc.bat>>_package.lst
    if exist gaggle\stamp_generate echo gaggle\stamp_generate>>_package.lst
    if exist gaggle\boomakew.bat echo gaggle\boomakew.bat>>_package.lst
    if exist gaggle\configure echo gaggle\configure>>_package.lst
    if exist gaggle\Makefile.unix echo gaggle\Makefile.unix>>_package.lst
    if exist gaggle\boomake echo gaggle\boomake>>_package.lst
    if exist gaggle\configure.bat echo gaggle\configure.bat>>_package.lst
    if exist gaggle\Makefile.win32 echo gaggle\Makefile.win32>>_package.lst
    if exist gaggle\boomake.bat echo gaggle\boomake.bat>>_package.lst
    pushd libero
    popd
    if exist libero\version.h echo libero\version.h>>_package.lst
    if exist libero\lr.c echo libero\lr.c>>_package.lst
    if exist libero\lrcalc.c echo libero\lrcalc.c>>_package.lst
    if exist libero\lreval.c echo libero\lreval.c>>_package.lst
    if exist libero\lrcode.c echo libero\lrcode.c>>_package.lst
    if exist libero\lrload.c echo libero\lrload.c>>_package.lst
    if exist libero\lrdump.c echo libero\lrdump.c>>_package.lst
    if exist libero\lrfree.c echo libero\lrfree.c>>_package.lst
    if exist libero\lrsort.c echo libero\lrsort.c>>_package.lst
    if exist libero\lrglib.c echo libero\lrglib.c>>_package.lst
    if exist libero\lrlibr.c echo libero\lrlibr.c>>_package.lst
    if exist libero\lroptn.c echo libero\lroptn.c>>_package.lst
    if exist libero\lrsymb.c echo libero\lrsymb.c>>_package.lst
    if exist libero\lrpriv.h echo libero\lrpriv.h>>_package.lst
    if exist libero\lrschema.asm echo libero\lrschema.asm>>_package.lst
    if exist libero\lrschema.awk echo libero\lrschema.awk>>_package.lst
    if exist libero\lrschema.bsh echo libero\lrschema.bsh>>_package.lst
    if exist libero\lrschema.c echo libero\lrschema.c>>_package.lst
    if exist libero\lrschema.c99 echo libero\lrschema.c99>>_package.lst
    if exist libero\lrschema.cob echo libero\lrschema.cob>>_package.lst
    if exist libero\lrschema.cpp echo libero\lrschema.cpp>>_package.lst
    if exist libero\lrschema.cs echo libero\lrschema.cs>>_package.lst
    if exist libero\lrschema.csh echo libero\lrschema.csh>>_package.lst
    if exist libero\lrschema.jav echo libero\lrschema.jav>>_package.lst
    if exist libero\lrschema.ksh echo libero\lrschema.ksh>>_package.lst
    if exist libero\lrschema.mst echo libero\lrschema.mst>>_package.lst
    if exist libero\lrschema.pas echo libero\lrschema.pas>>_package.lst
    if exist libero\lrschema.pl echo libero\lrschema.pl>>_package.lst
    if exist libero\lrservice.pl echo libero\lrservice.pl>>_package.lst
    if exist libero\lrschema.py echo libero\lrschema.py>>_package.lst
    if exist libero\lrschema.php echo libero\lrschema.php>>_package.lst
    if exist libero\lrschema.rex echo libero\lrschema.rex>>_package.lst
    if exist libero\lrschema.sh echo libero\lrschema.sh>>_package.lst
    if exist libero\lrschema.sql echo libero\lrschema.sql>>_package.lst
    if exist libero\lrschema.vb echo libero\lrschema.vb>>_package.lst
    if exist libero\lrmesg.txt echo libero\lrmesg.txt>>_package.lst
    if exist libero\prelude.h echo libero\prelude.h>>_package.lst
    if exist libero\lr.ini echo libero\lr.ini>>_package.lst
    if exist libero\lr_eg.ini echo libero\lr_eg.ini>>_package.lst
    if exist libero\template echo libero\template>>_package.lst
    if exist libero\prelude.pdl echo libero\prelude.pdl>>_package.lst
    if exist libero\license.gpl echo libero\license.gpl>>_package.lst
    if exist libero\project.pdl echo libero\project.pdl>>_package.lst
    if exist libero\readme.txt echo libero\readme.txt>>_package.lst
    if exist libero\lrcalc.l echo libero\lrcalc.l>>_package.lst
    if exist libero\lrcalc.i echo libero\lrcalc.i>>_package.lst
    if exist libero\lrcalc.d echo libero\lrcalc.d>>_package.lst
    if exist libero\lreval.l echo libero\lreval.l>>_package.lst
    if exist libero\lreval.i echo libero\lreval.i>>_package.lst
    if exist libero\lreval.d echo libero\lreval.d>>_package.lst
    if exist libero\lrcode.l echo libero\lrcode.l>>_package.lst
    if exist libero\lrcode.i echo libero\lrcode.i>>_package.lst
    if exist libero\lrcode.d echo libero\lrcode.d>>_package.lst
    if exist libero\lrload.l echo libero\lrload.l>>_package.lst
    if exist libero\lrload.i echo libero\lrload.i>>_package.lst
    if exist libero\lrload.d echo libero\lrload.d>>_package.lst
    if exist libero\lrglib.h echo libero\lrglib.h>>_package.lst
    if exist libero\lrlibr.h echo libero\lrlibr.h>>_package.lst
    if exist libero\lroptn.h echo libero\lroptn.h>>_package.lst
    if exist libero\lrsymb.h echo libero\lrsymb.h>>_package.lst
    if exist libero\stamp_generate echo libero\stamp_generate>>_package.lst
    if exist libero\boomakew.bat echo libero\boomakew.bat>>_package.lst
    if exist libero\configure echo libero\configure>>_package.lst
    if exist libero\Makefile.unix echo libero\Makefile.unix>>_package.lst
    if exist libero\boomake echo libero\boomake>>_package.lst
    if exist libero\configure.bat echo libero\configure.bat>>_package.lst
    if exist libero\Makefile.win32 echo libero\Makefile.win32>>_package.lst
    if exist libero\boomake.bat echo libero\boomake.bat>>_package.lst
    if exist libero\lr.vcproj echo libero\lr.vcproj>>_package.lst
    if exist libero\liblr.vcproj echo libero\liblr.vcproj>>_package.lst
    echo "Source package successfully generated">htmlpp\stamp_source
    echo "htmlpp\stamp_source">>_package.lst
    echo "Source package successfully generated">gurudoc\stamp_source
    echo "gurudoc\stamp_source">>_package.lst
    echo "Source package successfully generated">gaggle\stamp_source
    echo "gaggle\stamp_source">>_package.lst
    echo "Source package successfully generated">libero\stamp_source
    echo "libero\stamp_source">>_package.lst
    echo "Source package successfully generated">stamp_source
    echo "stamp_source">>_package.lst
    echo boom I: [base1]: Building base1-!MY_VERSION!-src.zip...
    zip  -rq _package -@<_package.lst
    unzip -q _package -d base1-!MY_VERSION!
    if exist  base1-!MY_VERSION!-src.zip del base1-!MY_VERSION!-src.zip
    zip -rmq base1-!MY_VERSION!-src.zip base1-!MY_VERSION!
    del _package.zip
    del _package.lst
    del stamp_source
    del htmlpp\stamp_source
    del gurudoc\stamp_source
    del gaggle\stamp_source
    del libero\stamp_source
    goto :eof

:-----------------------------   BUILD PROJECTS   -----------------------------

:a_build_projects
    if exist _install\nul rmdir /s /q _install
    mkdir _install
    mkdir _install\lib
    mkdir _install\include
    mkdir _install\bin
    pushd htmlpp
    if exist boomake.bat (
        call boomake -install ..\_install build install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gurudoc
    if exist boomake.bat (
        call boomake -install ..\_install build install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gaggle
    if exist boomake.bat (
        call boomake -install ..\_install build install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd libero
    if exist boomake.bat (
        call boomake -install ..\_install build install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    goto :eof

:-------------------------   CHECK OPERATING CONTEXT   ------------------------

:a_check_operating_context
    set event=repository
    if exist stamp_source   set event=source
    if exist stamp_stripped set event=stripped
    goto :eof

:-----------------------------   CLEAN PROJECTS   -----------------------------

:a_clean_projects
    if exist _install\nul rmdir /s /q _install
    pushd htmlpp
    if exist boomake.bat (
        call boomake clean
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gurudoc
    if exist boomake.bat (
        call boomake clean
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gaggle
    if exist boomake.bat (
        call boomake clean
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd libero
    if exist boomake.bat (
        call boomake clean
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    goto :eof

:----------------------------   COMPILE PROJECTS   ----------------------------

:a_compile_projects
    pushd htmlpp
    if exist boomake.bat (
        call boomake compile
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gurudoc
    if exist boomake.bat (
        call boomake compile
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gaggle
    if exist boomake.bat (
        call boomake compile
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd libero
    if exist boomake.bat (
        call boomake compile
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    goto :eof

:----------------------------   INSTALL PROJECTS   ----------------------------

:a_install_projects
    pushd htmlpp
    if exist boomake.bat (
        call boomake install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gurudoc
    if exist boomake.bat (
        call boomake install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gaggle
    if exist boomake.bat (
        call boomake install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd libero
    if exist boomake.bat (
        call boomake install
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    if exist installer.bat (
    if "!BOOM_TRACE!"=="1" echo installer
    verify>nul
    call installer
    if errorlevel 1 (
        echo boom E: [base1]: 'installer' failed - stop.
        set _exception=1
        goto :eof
    )
    )
    goto :eof

:-----------------------------   REGEN PROJECTS   -----------------------------

:a_regen_projects
    pushd htmlpp
    if exist boomake.bat (
        call boomake regen
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gurudoc
    if exist boomake.bat (
        call boomake regen
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gaggle
    if exist boomake.bat (
        call boomake regen
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd libero
    if exist boomake.bat (
        call boomake regen
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    goto :eof

:-------------------------   REPORT HELP INFORMATION   ------------------------

:a_report_help_information
    echo The commands you can currently use on this project are:
    echo.
    goto r_!state!
    goto :eof

:-------------------------   REPORT PROJECT VERSION   -------------------------

:a_report_project_version
    echo base1-1.2e0
    goto :eof

:------------------------------   TEST PROJECTS   -----------------------------

:a_test_projects
    pushd htmlpp
    if exist boomake.bat (
        call boomake test
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gurudoc
    if exist boomake.bat (
        call boomake test
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd gaggle
    if exist boomake.bat (
        call boomake test
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    pushd libero
    if exist boomake.bat (
        call boomake test
    ) else (
        echo boom E: [base1]: project is not configured - run 'boom configure'
    )
    popd
    if exist selftest.bat (
    if "!BOOM_TRACE!"=="1" echo selftest
    verify>nul
    call selftest
    if errorlevel 1 (
        echo boom E: [base1]: 'selftest' failed - stop.
        set _exception=1
        goto :eof
    )
    )
    goto :eof

:-----------------------   USE SOURCE CONTROL REVISION   ----------------------

:a_use_source_control_revision
    set SVN_REVISION=svn
    if exist .svn
ul (
        for /f "usebackq tokens=1,2 delims=: " %%v in (`svn info`) do if "%%v"=="Revision" set SVN_REVISION=%%w
    )
    set MY_VERSION=!MY_VERSION!-!SVN_REVISION!
    goto :eof

:s_initial
    if "!debug!"=="1" echo State: initial
    if "!event!"=="" goto s_1_empty
    if "!event!"=="ok" goto s_1_1
    echo Unknown command - use one of:
    echo.
    goto r_!state!
:s_1_1
    if "!debug!"=="1" echo Event: ok
    set event=
    if "!debug!"=="1" echo Action: check operating context
    set _exception=
    call :a_check_operating_context
    if "!_exception!"=="1" exit /b 1
    set state=initial_check
    goto s_!state!
:s_1_empty
    if "!debug!"=="1" echo Get event from user
    set event=%1
    shift
    if "!event!"=="" set event=empty
    goto s_initial
:r_initial
    exit /b 0

:s_initial_check
    if "!debug!"=="1" echo State: initial check
    if "!event!"=="" goto s_2_empty
    if "!event!"=="repository" goto s_2_1
    if "!event!"=="source" goto s_2_2
    if "!event!"=="stripped" goto s_2_3
    echo Unknown command - use one of:
    echo.
    goto r_!state!
:s_2_1
    if "!debug!"=="1" echo Event: repository
    set event=
    set state=repository
    goto s_!state!
:s_2_2
    if "!debug!"=="1" echo Event: source
    set event=
    set state=source
    goto s_!state!
:s_2_3
    if "!debug!"=="1" echo Event: stripped
    set event=
    set state=stripped
    goto s_!state!
:s_2_empty
    if "!debug!"=="1" echo Get event from user
    set event=%1
    shift
    if "!event!"=="" set event=empty
    goto s_initial_check
:r_initial_check
    exit /b 0

:s_repository
    if "!debug!"=="1" echo State: repository
    if "!event!"=="" goto s_3_empty
    if "!event!"=="build" goto s_3_1
    if "!event!"=="compile" goto s_3_2
    if "!event!"=="clean" goto s_3_3
    if "!event!"=="regen" goto s_3_4
    if "!event!"=="allgen" goto s_3_5
    if "!event!"=="distrib" goto s_3_6
    if "!event!"=="distsrc" goto s_3_7
    if "!event!"=="distrev" goto s_3_8
    goto s_default
:s_3_1
    if "!debug!"=="1" echo Event: build
    set event=
    if "!debug!"=="1" echo Action: build projects
    set _exception=
    call :a_build_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_3_2
    if "!debug!"=="1" echo Event: compile
    set event=
    if "!debug!"=="1" echo Action: compile projects
    set _exception=
    call :a_compile_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_3_3
    if "!debug!"=="1" echo Event: clean
    set event=
    if "!debug!"=="1" echo Action: clean projects
    set _exception=
    call :a_clean_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_3_4
    if "!debug!"=="1" echo Event: regen
    set event=
    if "!debug!"=="1" echo Action: regen projects
    set _exception=
    call :a_regen_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_3_5
    if "!debug!"=="1" echo Event: allgen
    set event=
    if "!debug!"=="1" echo Action: allgen projects
    set _exception=
    call :a_allgen_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_3_6
    if "!debug!"=="1" echo Event: distrib
    set event=
    if "!debug!"=="1" echo Action: build projects
    set _exception=
    call :a_build_projects
    if "!_exception!"=="1" exit /b 1
    if "!debug!"=="1" echo Action: build product source packages
    set _exception=
    call :a_build_product_source_packages
    if "!_exception!"=="1" exit /b 1
    if "!debug!"=="1" echo Action: build product install packages
    set _exception=
    call :a_build_product_install_packages
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_3_7
    if "!debug!"=="1" echo Event: distsrc
    set event=
    if "!debug!"=="1" echo Action: allgen projects
    set _exception=
    call :a_allgen_projects
    if "!_exception!"=="1" exit /b 1
    if "!debug!"=="1" echo Action: build product source packages
    set _exception=
    call :a_build_product_source_packages
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_3_8
    if "!debug!"=="1" echo Event: distrev
    set event=
    if "!debug!"=="1" echo Action: allgen projects
    set _exception=
    call :a_allgen_projects
    if "!_exception!"=="1" exit /b 1
    if "!debug!"=="1" echo Action: use source control revision
    set _exception=
    call :a_use_source_control_revision
    if "!_exception!"=="1" exit /b 1
    if "!debug!"=="1" echo Action: build product source packages
    set _exception=
    call :a_build_product_source_packages
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_3_empty
    if "!debug!"=="1" echo Get event from user
    set event=%1
    shift
    if "!event!"=="" set event=empty
    goto s_repository
:r_repository
echo build:
    echo   For each project in the product, regenerate code and build binary
    echo     files ready for installation.  The projects are built in their
    echo     individual directories and installed into the temporary install tree.
echo compile:
    echo   For each project in the product, build binary files ready for installation,
    echo     but don't run the code generation phase .  The projects are built in their
    echo     individual directories and installed into the temporary install tree.
echo clean:
    echo   Deletes generated project files.  This action removes generated source
    echo     and binary files.
echo regen:
    echo   For each project in the product, regenerate any source files that
    echo     are produced via GSL, Libero or another code generation tool.
    echo     Generates only those files that are required to build under
    echo     the current model.
echo allgen:
    echo   For each project in the product, regenerate any source files that
    echo     are produced via GSL, Libero or another code generation tool.
    echo     Generates all files.
echo distrib:
    echo   Build all projects and create full distribution packages.  If you do
    echo     not want to rebuild the projects, you can use the 'distsrc' and 'distbin'
    echo     actions as shortcuts.
echo distsrc:
    echo   Build source distribution packages based on product version number.
echo distrev:
    echo   Build source distribution packages based on source control revision
    echo     number.
    goto r_default

:s_source
    if "!debug!"=="1" echo State: source
    if "!event!"=="" goto s_4_empty
    if "!event!"=="build" goto s_4_1
    if "!event!"=="clean" goto s_4_2
    if "!event!"=="regen" goto s_4_3
    if "!event!"=="allgen" goto s_4_4
    goto s_default
:s_4_1
    if "!debug!"=="1" echo Event: build
    set event=
    if "!debug!"=="1" echo Action: build projects
    set _exception=
    call :a_build_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_4_2
    if "!debug!"=="1" echo Event: clean
    set event=
    if "!debug!"=="1" echo Action: clean projects
    set _exception=
    call :a_clean_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_4_3
    if "!debug!"=="1" echo Event: regen
    set event=
    if "!debug!"=="1" echo Action: regen projects
    set _exception=
    call :a_regen_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_4_4
    if "!debug!"=="1" echo Event: allgen
    set event=
    if "!debug!"=="1" echo Action: allgen projects
    set _exception=
    call :a_allgen_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_4_empty
    if "!debug!"=="1" echo Get event from user
    set event=%1
    shift
    if "!event!"=="" set event=empty
    goto s_source
:r_source
echo build:
    echo   For each project in the product, build binary files ready for
    echo     installation.  The projects are built in their individual directories
    echo     and installed into the temporary install tree.
echo clean:
    echo   Deletes generated project files.  This action removes generated binary
    echo     files.
echo regen:
    echo   For each project in the product, regenerate any source files that
    echo     are produced via GSL, Libero or another code generation tool.
    echo     Generates only those files that are required to build under
    echo     the current model.
echo allgen:
    echo   For each project in the product, regenerate any source files that
    echo     are produced via GSL, Libero or another code generation tool.
    echo     Generates all files.
    goto r_default

:s_stripped
    if "!debug!"=="1" echo State: stripped
    if "!event!"=="" goto s_5_empty
    if "!event!"=="build" goto s_5_1
    if "!event!"=="clean" goto s_5_2
    goto s_default
:s_5_1
    if "!debug!"=="1" echo Event: build
    set event=
    if "!debug!"=="1" echo Action: build projects
    set _exception=
    call :a_build_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_5_2
    if "!debug!"=="1" echo Event: clean
    set event=
    if "!debug!"=="1" echo Action: clean projects
    set _exception=
    call :a_clean_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_5_empty
    if "!debug!"=="1" echo Get event from user
    set event=%1
    shift
    if "!event!"=="" set event=empty
    goto s_stripped
:r_stripped
echo build:
    echo   For each project in the product, build binary files ready for
    echo     installation.  The projects are built in their individual directories
    echo     and installed into the temporary install tree.
echo clean:
    echo   Deletes generated project files.  This action removes generated binary
    echo     files.
    goto r_default

:s_default
    if "!debug!"=="1" echo State: default
    if "!event!"=="" goto s_6_empty
    if "!event!"=="install" goto s_6_1
    if "!event!"=="distbin" goto s_6_2
    if "!event!"=="test" goto s_6_3
    if "!event!"=="help" goto s_6_4
    if "!event!"=="version" goto s_6_5
    if "!event!"=="empty" goto s_6_6
    echo Unknown command - use one of:
    echo.
    goto r_!state!
:s_6_1
    if "!debug!"=="1" echo Event: install
    set event=
    if "!debug!"=="1" echo Action: install projects
    set _exception=
    call :a_install_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_6_2
    if "!debug!"=="1" echo Event: distbin
    set event=
    if "!debug!"=="1" echo Action: build product install packages
    set _exception=
    call :a_build_product_install_packages
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_6_3
    if "!debug!"=="1" echo Event: test
    set event=
    if "!debug!"=="1" echo Action: test projects
    set _exception=
    call :a_test_projects
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_6_4
    if "!debug!"=="1" echo Event: help
    set event=
    if "!debug!"=="1" echo Action: report help information
    set _exception=
    call :a_report_help_information
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_6_5
    if "!debug!"=="1" echo Event: version
    set event=
    if "!debug!"=="1" echo Action: report project version
    set _exception=
    call :a_report_project_version
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_6_6
    if "!debug!"=="1" echo Event: empty
    set event=
    if "!debug!"=="1" echo Action: report help information
    set _exception=
    call :a_report_help_information
    if "!_exception!"=="1" exit /b 1
    if not "%1"=="" goto process
    exit /b 0
:s_6_empty
    if "!debug!"=="1" echo Get event from user
    set event=%1
    shift
    if "!event!"=="" set event=empty
    goto s_default
:r_default
echo install:
    echo   Install each project into its target directory.  The projects must
    echo     have been built (and installed into the temporary install tree, which
    echo     is what the build action does).
echo distbin:
    echo   Build binary distribution packages.  The actual packages built depend on
    echo     the project packagers used, but typically you will get a ZIP or TGZ file
    echo     containing all the projects' deliverables.  Note that this action works
    echo     entirely from the temporary install tree, which the 'build' action makes.
echo test:
    echo   Runs each project's test process.
echo help:
    echo   Shows a list of the commands allowed on the project.
echo version:
    echo   Show product version.
    exit /b 0


exit /b 0
